on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run the Action
      id: home
      uses: ./
      with:
        myInput: 'Bishwajeett Uday Samanta'
    - name: Output
      run: |
        echo ${{ steps.home.outputs.memory }}
        echo "Total Memory Logged Successfully"
